services:
  postgres:
    image: postgres:16
    container_name: booklab-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=booklab
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mivu"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: booklabServer
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=booklab
    ports:
      - "5500:5500"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  web_ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: booklabUi
    ports:
      - "90:90"
    environment:
      - VITE_API_PATH=http://localhost:5500
    depends_on:
      - backend_server
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
